version: '3.9'

services:
  arena:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    # Monta la carpeta 'public' del host en el contenedor para persistencia y para que se sirvan los assets
    volumes:
      - ./public:/app/public
